### ISSUE TITLE
Multi-line task list items don't properly indent

### ISSUE THREAD

**Issue by SharpSeeEr** [neilsustc/vscode-markdown#203]
## Problem Summary

When a task list item is very long and wraps to a new line the additional lines are not indented to align with the text on the first line.  Instead the text is aligned with the checkbox.

## Reproducing the Problem

The following markdown:

```markdown
### Task List Alignment Issue

- [ ] Single line task
- [ ] Multiple line task.  Because I have a whole lot to explain for this task, as it is potentially exceptionally complex, and I am putting it all on one task list item even though I would probably be better suited to splitting it into multiple tasks or sub tasks.  Phew!
- [ ] Another single line task
```

Renders like this:
![image](https://user-images.githubusercontent.com/4459909/41209118-a1b4bebc-6ce6-11e8-8bcc-6b63d3870b30.png)

## Console Error

There is an error in the console but I don't think it is related to this issue.  Here it is anyway, just in case.

```
[Extension Host] [vscode.markdown-language-features] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for '[markdown]', provide the URI of a resource or 'null' for any resource.
t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:393
(anonymous) @ extensionHost.ts:210
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
```

**Comment by neilsustc** [comment]
Fixed in the latest CI build. You can find the download link at the end of `README`.

**Comment by SharpSeeEr** [comment]
Thanks!
